import {Options} from './shared/model';

export interface ChangeOptionsRequest {
  options: Options;
}

export enum ErrorCode {
  NO_SUCH_USER = 'NO_SUCH_USER',
  EXCEEDS_MAX_REALTIME_GAMES = 'EXCEEDS_MAX_REALTIME_GAMES',
  CANNOT_INVITE_YOURSELF = 'CANNOT_INVITE_YOURSELF',
  GAME_ALREADY_STARTED_OR_ENDED = 'GAME_ALREADY_STARTED_OR_ENDED',
  GAME_NOT_STARTED = 'GAME_NOT_STARTED',
  NOT_INVITED = 'NOT_INVITED',
  ALREADY_RESPONDED = 'ALREADY_RESPONDED',
  MUST_BE_OWNER = 'MUST_BE_OWNER',
  NOT_PLAYER_IN_GAME = 'NOT_PLAYER_IN_GAME',
  NOT_YOUR_TURN = 'NOT_YOUR_TURN',
  MUST_SPECIFY_USERNAME_OR_EMAIL = 'MUST_SPECIFY_USERNAME_OR_EMAIL',
  MIN_PLAYERS = 'MIN_PLAYERS',
  EXCEEDS_MAX_PLAYERS = 'EXCEEDS_MAX_PLAYERS',
  GAME_ALREADY_ENDED = 'GAME_ALREADY_ENDED',
  NOT_ACCEPTED = 'NOT_ACCEPTED',
  CANNOT_ABANDON = 'CANNOT_ABANDON',
  GAME_ABANDONED = 'GAME_ABANDONED',
  ALREADY_INVITED = 'ALREADY_INVITED',
  NOT_SUPPORTED = 'NOT_SUPPORTED',
  USERNAME_TOO_SHORT = 'USERNAME_TOO_SHORT',
  USERNAME_TOO_LONG = 'USERNAME_TOO_LONG',
  USERNAME_INVALID_CHARS = 'USERNAME_INVALID_CHARS',
  USERNAME_FORBIDDEN = 'USERNAME_FORBIDDEN',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  IN_GAME_ERROR = 'IN_GAME_ERROR',
  COMPUTER_NOT_SUPPORTED = 'COMPUTER_NOT_SUPPORTED',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}

export interface ErrorResponse {
  errorCode: ErrorCode;
  gameId?: string;
  reasonCode?: string;
}

export interface AddFriendRequest {
  userId: string;
}

export interface Game {
  id: string;
  minNumberOfPlayers: number;
  maxNumberOfPlayers: number;
  computerSupport: boolean;
}
